-- Printing 'customer' table till 20 rows
select * from customer limit 20

--1. What is the total revenue generated by male vs. female customers?
select gender,SUM(purchase_amount) as revenue
from customer
group by gender

--2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type

--5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;

--7. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--8. What is the revenue contribution of each age group? 
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
